<?php

namespace App\Models;

use function foo\func;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    
    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        
        static::creating(function($category){
            $category->slug = str_slug($category->name);
        });
    }
    
    public function posts(){
        return $this->hasMany('App\Models\Post','categoryId');
    }
}
