<?php

namespace App\Models;

use App\Events\PostEvent;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    protected $guarded = [];
    
    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        
        static::creating(function($post){
            $title = preg_replace('/([+,:;=$&?@])/','',$post->title);
            $post->slug = preg_replace('/\s+/u', '-', trim($title));
        });
    }
    
    protected $dispatchesEvents = [
        'saved' => PostEvent::class,
        'deleted' => PostEvent::class,
        'updated' => PostEvent::class,
    ];
    
    public function category(){
        return $this->belongsTo('App\Models\Category','categoryId');
    }
    
    public function getCreatedAtAttribute($value) {
        return Carbon::parse($value)->format('M d, Y');
    }
    
    /**
     * Get all of the tags for the post.
     */
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }
    
    public function comments(){
        return $this->hasMany('App\Models\Comment','post_id');
    }
}
