<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class QuestionType extends Model
{
    protected $guarded = [];
    
    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        
        static::creating(function($type){
            $title = preg_replace('/([+,:;=$&?@])/','',$type->type);
            $type->slug = preg_replace('/\s+/u', '-', trim($title));
        });
    }
    
    public function questions(){
        // return $this->morphedByMany(Question::class,'questionable');
        return $this->morphToMany(Question::class,'questionable');
    }
}
