<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Symfony\Component\Console\Question\Question;

class Quiz extends Model
{
    protected $guarded = [];
    
    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        
        static::creating(function($quiz) {
            ;
            $name = preg_replace('/([+,:;=$&?@])/', '', $quiz->name);
            $quiz->slug = strtolower(preg_replace('/\s+/u', '-', trim($name)));
        });
    }

    public function posts(){
        return $this->belongsTo(Post::class,'post_id');
    }

    public function questions(){
        return $this->hasMany(Question::class,'quiz_id');
    }
}
